global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-2
        access_key: AKIA5MYDLG5VXYGL7WWS
        secret_key: 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
        port: 9100
